// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCePTFntKITphxhjszAN2BWhYEkLdxB6X4',
    appId: '1:625724453137:web:f670020ff866ddc2c45cb0',
    messagingSenderId: '625724453137',
    projectId: 'flutter-test-d1cb6',
    authDomain: 'flutter-test-d1cb6.firebaseapp.com',
    storageBucket: 'flutter-test-d1cb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCTC4IG0Lzq42q0k4CeeHTqsgksbiuv3A',
    appId: '1:625724453137:android:f8532f506dd917c2c45cb0',
    messagingSenderId: '625724453137',
    projectId: 'flutter-test-d1cb6',
    storageBucket: 'flutter-test-d1cb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiHRAXj__ad7AjhJ-jNGTz9lm4c8ZXEu0',
    appId: '1:625724453137:ios:101bb8fb100ecd6fc45cb0',
    messagingSenderId: '625724453137',
    projectId: 'flutter-test-d1cb6',
    storageBucket: 'flutter-test-d1cb6.appspot.com',
    iosClientId: '625724453137-9bt3jba010a7ogp7bsrc1egv102l9luj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiHRAXj__ad7AjhJ-jNGTz9lm4c8ZXEu0',
    appId: '1:625724453137:ios:fe5dc362bcc03f13c45cb0',
    messagingSenderId: '625724453137',
    projectId: 'flutter-test-d1cb6',
    storageBucket: 'flutter-test-d1cb6.appspot.com',
    iosClientId: '625724453137-jd68doeh8h7gk016if1p0hfvu46aipbq.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttapp.RunnerTests',
  );
}
